export const constants = {
  BLACK_ROOK1:"BLACK_ROOK1",
  BLACK_ROOK2:"BLACK_ROOK2",
  WHITE_ROOK1:"WHITE_ROOK1",
  WHITE_ROOK2:"WHITE_ROOK2",
  WHITE_KNIGHT1:"WHITE_KNIGHT1",
  WHITE_KNIGHT2:"WHITE_KNIGHT2",
  BLACK_KNIGHT1:"BLACK_KNIGHT1",
  BLACK_KNIGHT2:"BLACK_KNIGHT2",
}